### ISSUE TITLE
Button should be disabled if text field is empty

### ISSUE THREAD

**Issue by ungb** [atom/teletype#131]
This is minor but can be a usability issue as I don't think the scenarios where the text field is empty are valid.  Buttons should be disabled when field is empty.

Enter your Token:
![image](https://user-images.githubusercontent.com/5624870/32023087-20d13e40-b98d-11e7-8f91-cb9be29c1d50.png)

Joining Portal:

![image](https://user-images.githubusercontent.com/5624870/32023127-41ae1d40-b98d-11e7-8a82-d555d6ebed73.png)

**Comment by jasonrudolph** [comment]
Closed by https://github.com/atom/teletype/pull/248. These improvements will go out in the next release.

**Comment by Ben3eeE** [comment]
@jasonrudolph It looks like you intended to close this issue but clicked the wrong button :slightly_smiling_face: Please reopen I am misunderstanding something!
