### ISSUE TITLE
Audit startup time impact

### ISSUE THREAD

**Issue by nathansobo** [atom/teletype#136]
Saw this today:

![screen shot 2017-10-26 at 9 51 02 am](https://user-images.githubusercontent.com/1789/32062959-3e9c8bfe-ba33-11e7-817d-4f7996cd592b.png)

Since we won't be bundling this package initially, it may be worth looking into how to minimize its impact on startup time.

**Comment by jasonrudolph** [comment]
Closing in favor of #201.

**Comment by 50Wliu** [comment]
Sorry!  Didn't think of searching issues because of how new this package was :/.
