### ISSUE TITLE
Pusher warning: "You should always specify a cluster when connecting"

### ISSUE THREAD

**Issue by jasonrudolph** [atom/teletype#138]
Recently, we've started seeing the following warning from pusher in the dev console:

> Pusher : You should always specify a cluster when connecting. See: https://pusher.com/docs/javascript_quick_start

![screen shot 2017-10-26 at 3 41 46 pm](https://user-images.githubusercontent.com/2988/32073489-40bf22d0-ba64-11e7-8fed-1ada95bbe69d.png)

**Comment by jasonrudolph** [comment]
Closing in favor of https://github.com/atom/teletype/issues/202.

**Comment by Arcanemagus** [comment]
Whoops, forgot to search for existing issues, sorry! I would have gone the other way and marked #202 as a dupe of this personally 😛.
