### ISSUE TITLE
Opening untitled window and saving file should update file name to guest as well

### ISSUE THREAD

**Issue by ungb** [atom/teletype#147]
Repro steps:

1. Open Atom
1. Share portal with someone else. 
1. Host opens a new untitled window.
1. Host saves file as `loader.js` or something

**Expected:** Guest should have their buffer updated to reflect the new file name, file path, and grammar.

**Actual:**
Still shows untitled, Clicking away will show untitled for guest.  If you close the file and open it again it will be updated.

See screenshot:

![image](https://user-images.githubusercontent.com/5624870/32082093-14f3266a-ba6e-11e7-95b3-b0e44cbf751f.png)

Atom version:
Atom    : 1.23.0-dev-26817c613
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

real-time sha: e34170c64b9fab5b07423436e5f09a772b0e0b4b

/cc @Ben3eeE

**Comment by ungb** [comment]
This is still an issue with https://github.com/atom/teletype/pull/262.  

1. Host creates a new untitled tab
1. Guest is following host.
1. Host names file as foo.md
1. Guest closes the untitled tab and clicks follow host to get the tab back


Expected: shows correct file name


Actual: Shows untitled still.

**Comment by jasonrudolph** [comment]
> This is still an issue with #262.

That's right. #262 wasn't focused on resolving this issue, but we would still like to address it. 👌

**Comment by CaptainJohnyAppleSeed** [comment]
We have made a proposed solution to this issue [here](https://github.com/atom/teletype/issues/336). Any thoughts?

**Comment by jasonrudolph** [comment]
Closed by https://github.com/atom/teletype/pull/341. You can see a demo below, in which the top window is the host, and the bottom window is a guest.

![demo](https://user-images.githubusercontent.com/2988/38276245-5afb6764-3762-11e8-868a-f5da6616a753.gif)

This improvement will be included in the next release.
