### ISSUE TITLE
Jarring experience when the host switches the editor while the guest is typing

### ISSUE THREAD

**Issue by nathansobo** [atom/teletype#168]
After experiencing it first hand, it's really jarring to follow the host to a different editor in the middle of typing. I wonder if it might make sense to leave the guest on the original editor and allow them to catch back up with the host by clicking the host's icon.

The downside is that we're creeping into more complex territory where portal participants could end up looking at different editors. It's a slippery slope to adding increasing levels of navigation control that I worry could get complicated. But maybe if the only navigation affordance is clicking on the avatar of another user, we could get by without tearing users away from their editor in the middle of typing.

**Comment by VariableClass** [comment]
:+1:

**Comment by lkraav** [comment]
https://togetherjs.com for example announces remote user navigation actions w/ message popups.

"joe has navigated to page https://example.com/bar/"

**Comment by jasonrudolph** [comment]
> After experiencing it first hand, it's really jarring to follow the host to a different editor in the middle of typing. I wonder if it might make sense to leave the guest on the original editor and allow them to catch back up with the host by clicking the host's icon.

This should be resolved now (as of [Teletype 0.3.0](https://github.com/atom/teletype/releases/tag/v0.3.0)). If you're actively typing in Editor A, and the host switches to a Editor B, your focus remains in Editor A.
