### ISSUE TITLE
Follower goes to a different position

### ISSUE THREAD

**Issue by Ben3eeE** [atom/teletype#176]
**Note:** Not sure if this is expected and there is some behavior we didn't understand. The testing doc doesn't cover expected results for these cases.

**Steps to reproduce:**

1. Have guest follow host
1. Guest moves to another location using:
    - Autoscroll horizontally by making edits
    - Jumps to a bookmark using the bookmarks package
    - Jump to a different location using find-and-replace
    - Jump to a different location using the go to line package
    - Jump to a different location using symbols-view

**Expected:** Guest unfollows and the avatar updates.
**Actual:** Guest seems to unfollow but the chain follow icon is still shown. It moved to above the leader avatar.

![image](https://user-images.githubusercontent.com/734194/32462850-bae29dec-c2ef-11e7-83e7-ab547e9cb220.png)

/cc: @rsese

**Comment by odoyle71** [comment]
I was unable to replicate this on teletype (v0.6.0) and the most up to date atom version (1.23.3). This bug appears to be patched. @Ben3eeE can you confirm that you are still having this issue or can this be closed?

**Comment by Ben3eeE** [comment]
@odoyle71 Thank you for checking :bowing_man: I tested all of the cases and no longer observe this behavior on the latest version of teletype and Atom. So this issue can be closed :slightly_smiling_face:
