### ISSUE TITLE
Host can't click to follow if guest is following but guest can if host is following

### ISSUE THREAD

**Issue by Ben3eeE** [atom/teletype#177]
**Steps to reproduce:**

1. Have guest follow host
1. As host click to follow guest

**Expected:** Following guest?
**Actual:** Nothing happens

In reverse:

1. Have host follow guest
1. As guest click to follow host

**Expected and Actual:** Following host

/cc: @rsese

**Comment by xmsid** [comment]
The host and the guest follow each other, But the "link" icon that appears next to the avatar of the user you are following doesn't appear on the host side for some reason.

**Comment by jasonrudolph** [comment]
@Ben3eeE: Is this a duplicate of https://github.com/atom/teletype/issues/170? If not, can you say a bit more about how this issue differs from https://github.com/atom/teletype/issues/170?

**Comment by Ben3eeE** [comment]
@jasonrudolph I think you are correct that this is a duplicate of #170.
