### ISSUE TITLE
Attempting to share a portal failed with error: buffer.getHistory is not a function

### ISSUE THREAD

**Issue by barreeeiroo** [atom/teletype#190]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

I'm getting this error when trying to Share the code with this package:
`Attempting to share a portal failed with error: buffer.getHistory is not a function`

### Steps to Reproduce

1. Install atom/teletype
2. Open a file
3. Hit on the 'Broadcast Button'
4. After logging with the token hit 'Share'

**Expected behavior:**

To get a token to share the code live

**Actual behavior:**

Showed this error:
![image](https://user-images.githubusercontent.com/19251112/32853361-560c69e0-ca3b-11e7-95a0-cf4f8fbac0f3.png)

**Reproduces how often:**

Always

### Versions

- Atom Version: '1.21.0-beta0'
- Teletype Version: `0.1.1`

**Comment by as-cii** [comment]
Hello @barreeeiroo, and thanks for your feedback!

I see you're using Atom 1.21.0-beta0: have you tried running this on the latest stable (1.22) or beta version (1.23.0-beta0)? Thanks!

**Comment by nathansobo** [comment]
@as-cii maybe we should detect old versions and notify?

**Comment by jasonrudolph** [comment]
> maybe we should detect old versions and notify?

We can specify `>=1.22.0` in package.json, right? 

https://github.com/atom/teletype/blob/908ccdc786b1af9755ce9844b2f64d54d0309e25/package.json#L37

**Comment by nathansobo** [comment]
Hah duh of course

**Comment by as-cii** [comment]
Okay, I went ahead and specified Atom 1.22 as the minimum requirement for running teletype in 2230f47. This will be released with the next version of the package.

Thanks again for the report, @barreeeiroo! 🙇

**Comment by as-cii** [comment]
The fix for the issue has just been published on teletype v0.1.3. Thanks again for the report!

**Comment by barreeeiroo** [comment]
Thanks to you for this amazing Plugin for atom @as-cii 😉
