### ISSUE TITLE
Ability to Log Out

### ISSUE THREAD

**Issue by chriddyp** [atom/teletype#194]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

I accidentally shared my GitHub Token with a coworker (cc @cldougl!) instead of my atom portal ID. Now, my coworker is signed in as me. Is it possible for her to sign out?

### Steps to Reproduce

1. Sign in to teletype
2. Share token ID with another instance of atom
3. Uninstall and reinstall teletype - user is still signed in

**Expected behavior:**

To be able to sign out and re-sign in to github.

**Actual behavior:**

It doesn't seem possible right now to sign out and sign back in yet.

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.5.4
```
### Additional Information
This plug in is so awesome. Thanks for creating this!

**Comment by rsese** [comment]
Thanks for the report!  I think there's a couple of ways you can do it - what operating system is your coworker running?  If they're on macOS for example, you can delete the `atom-teletype` key from Keychain Access and then after restarting Atom, you should be asked to enter another token.

Alternatively, I think you can revoke `Teletype for Atom` from your account settings:

https://github.com/settings/applications

And then after restarting Atom you'll need to re-auth Teletype and you'll get another token.

**Comment by cldougl** [comment]
Thanks for the quick reply @rsese ! I am using macOS and deleting the `atom-teletype` key & restarting worked perfectly 👍

**Comment by DeltaGe** [comment]
What does one do for Windows? I can't seem to log out, reinstalled Teletype for Atom, and tried to deactivate Teletype. What else can I do?

**Comment by 50Wliu** [comment]
@DeltaGe search for "Credential Manager" and then click on "Windows Credentials".  I believe the one you want is `atom-teletype/oauth-token`.

**Comment by jasonrudolph** [comment]
A cross-platform option:

1. Find "Teletype for Atom" in your list of authorized applications on github.com.
   - You can go directly to the app via this link: https://github.com/settings/connections/applications/99c5a54e39feda31f25b
   - Alternatively, you can manually navigate to the app as described in this [this help article](https://help.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-oauth-apps)
2. Click the "Revoke" button to revoke access.
3. Reload Atom.
4. Click on the portal icon in the status bar. Teletype will recognize that your previous credentials are no longer valid, and Teletype will prompt you to log in.

**Comment by DeltaGe** [comment]
Thank you for your advice! 

We managed to sort things out!

**Comment by as-cii** [comment]
Thanks everyone for the reports! 🙇 The next version of teletype will provide an explicit command that will make it super easy to sign out (see https://github.com/atom/teletype/pull/244 for more information).

We will post an update here as soon as we publish a new version of teletype.

**Comment by laredo** [comment]
Still no luck - I was able to revoke the credentials and also reinstalled plugin - somehow my friend's credentials are still cached...

**Comment by jasonrudolph** [comment]
> We will post an update here as soon as we publish a new version of teletype.

teletype v0.2.2 is now available, and it includes the new "Teletype: Sign Out" command implemented in https://github.com/atom/teletype/pull/244.

@laredo: Can you try updating to teletype v0.2.2 and using this new command?
