### ISSUE TITLE
Can we edit github repo?

### ISSUE THREAD

**Issue by mittalyashu** [atom/teletype#196]
Can we edit GitHub repository without downloading or cloning it?

**Comment by Arcanemagus** [comment]
If you mean this repo itself, you can do so in the web interface on `github.com`.

**Comment by mittalyashu** [comment]
Yes, I know that.

But editing a remote repository on atom editor itself, it would be great.

**Comment by jasonrudolph** [comment]
At the moment, you can collaborate on any file that you can open in Atom. To collaborate on a github.com repository, the host would clone the repository, open it in Atom, and then share a portal.

We have aspirations for providing other collaboration scenarios, but we don't have any official plans in that area just yet.

**Comment by mittalyashu** [comment]
Yup. But isn't it a good idea. What do you think @jasoncwarner?

**Comment by jasonrudolph** [comment]
> But isn't it a good idea.

I think additional collaboration scenarios are a good idea. :smile:

If you are interested, we are working on an RFC (#231) that will allow participants to navigate among all the tabs a host has opened. If you have suggestions or comments, please do not hesitate to share them with us in that RFC. 🙇
