### ISSUE TITLE
Trim whitespace from portal ID on input

### ISSUE THREAD

**Issue by awilkins** [atom/teletype#197]
* Copy portal ID from e.g. Slack channel
* Accidentally grab some whitespace at the end
* Paste into "Join" dialog
* Times out
* Try again, only manually trim the space
* Works fine

**Comment by nathansobo** [comment]
This will be fixed with the next package release, *probably* tomorrow. Thanks for the report!

**Comment by as-cii** [comment]
The fix for this issue has just been published on teletype v0.1.3. ⚡️
