### ISSUE TITLE
Deactivating a packet does not work.

### ISSUE THREAD

**Issue by icetee** [atom/teletype#199]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

I click several times Disable / Enable button and always creates a new instance, no delete / clear old instance.

### Steps to Reproduce

1. Move Settings > Packages > Teletype
2. Click Disable
3. Click Enable
4. Points 2 and 3 again and again

**Expected behavior:**

Only one PortalStatusBarIndicator html element instance.

**Actual behavior:**

Create more-more instance.

**Reproduces how often:**

100%

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Teletype : 0.1.2

**Comment by 50Wliu** [comment]
@jasonrudolph this is what I meant by most of our packages not deactivating correctly :P.  I'll handle this one as well.

**Comment by as-cii** [comment]
Great job reporting these issues, @icetee. Thank you so much! ✨ 

Nice, @50Wliu: as usual, thanks for your amazing help! ⚡️
