### ISSUE TITLE
Feature Request: Join/share a portal via GitHub users

### ISSUE THREAD

**Issue by VariableClass** [atom/teletype#214]
### Join/share a portal via GitHub users

It would be nice to join or share a portal through some sort of mechanism using GitHub users. 🙂 

For example, selecting the user profile picture of a recently collaborated with/favourite user from within the Teletype interface would send them an e-mail via GitHub and/or flag a notification on the Teletype icon in Atom inviting them to collaborate.

[Atom Discussion thread](https://discuss.atom.io/t/teletype-join-share-a-portal-via-github-users/49753)

**Comment by jasonrudolph** [comment]
@VariableClass: Can you say a bit more about how this differs from https://github.com/atom/teletype/issues/213?
