### ISSUE TITLE
Cannot see host's file tree

### ISSUE THREAD

**Issue by suchipi** [atom/teletype#227]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

When I join a friend's teletype session, I cannot see their folder structure/file tree, and can only see the code they are editing (in one tab).

### Steps to Reproduce

1. On computer A, create a teletype session
1. On computer B, join the teletype session
1. Note that computer B cannot see the file tree (but computer A can).

**Expected behavior:**

I expected to see the host's open folders and files in my sidebar, and I expected to be able to open folders and files from their filesystem remotely in my own tabs.

**Actual behavior:**

The file tree sidebar did not appear, and pressing ^K^B to bring it up revealed that it was empty. When the host changed files, the one tab that was linked with the host would change to their new file.

**Reproduces how often:**

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Suchipi>atom --version

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

C:\Users\Suchipi>apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 ia32
python 2.7.6
git 2.10.0.windows.1
visual studio 2015
```

Windows 8.1

### Additional Information

N/A

**Comment by dest2013** [comment]
X

**Comment by rsese** [comment]
Thanks for the report!  You can collaborate only on a single file at the moment and there's no functionality around viewing the host's project tree view.

I think https://github.com/atom/teletype/issues/211 covers your request however so you can subscribe to that issue if you'd like.   You can also let us know that this enhancement would be useful for you by adding a 👍 emoji reaction to the [issue body](https://github.com/atom/teletype/issues/211#issue-274464843).

**Comment by fjorgemota** [comment]
I think that it's not a duplicate as #268 is now closed and in that issue @jasonrudolph describes that it would like to see integration with the tree-view, which this issue covers.

So..what do you think of opening this issue again so we can track the integration between teletype and tree-view package? =)

**Comment by jasonrudolph** [comment]
> So..what do you think of opening this issue again so we can track the integration between teletype and tree-view package? =)

@fjorgemota: I'd prefer to think of the problem holistically, and I think tracking this in https://github.com/atom/teletype/issues/211 will allow us to do so. If I'm misunderstanding, please let me know.
