### ISSUE TITLE
Failed to share portal

### ISSUE THREAD

**Issue by youngjuning** [atom/teletype#230]
Attempting to share a portal failed with error: Timed out while subscribing to incoming signals

**Comment by robertnicjoo** [comment]
same here

**Comment by as-cii** [comment]
Thanks for the report, @youngjuning and @robertnicjoo! 

Can you provide additional information regarding your network configuration? Anything that could cause connections to go wrong or that has been problematic for you in the past with other applications as well. The symptom looks very similar to #192, so I wonder if your computer is behind a proxy?

**Comment by as-cii** [comment]
I have posted more debug steps in https://github.com/atom/teletype/issues/192#issuecomment-345170237 that would help us track this down. Maybe you can follow those and report what you see? Thanks! 🙇

**Comment by NavneetSharmaPro** [comment]
Well I had the same issue and rebooting Atom fixed it. I was using it straight after install and I guess that's what was causing this error.

**Comment by robertnicjoo** [comment]
@as-cii Thank man it fixed by updates you released.

**Comment by as-cii** [comment]
Nice! Closing this as it seems to have been resolved. Thanks everyone for the reports! ⚡️

**Comment by AumPauskar** [comment]
> Attempting to share a portal failed with error: Timed out while subscribing to incoming signals

This may be due to the windows defender. Allow Atom/Teletype to use both private and public networks (honestly just selecting private networks may be enough but just to be absolutely sure you can do both).
