### ISSUE TITLE
how to share my folder  to others

### ISSUE THREAD

**Issue by iProgramme** [atom/teletype#232]
I want to share my folder to other people ,but I just know how to share one file

**Comment by as-cii** [comment]
Thanks for the feedback, @iProgramme! I am going to close this as a duplicate of #211.

If you are interested, we are working on a RFC (#231) that will allow participants to navigate among all the tabs a host has opened. If you have suggestions or comments, please do not hesitate to share them with us in that RFC. 🙇

**Comment by toewailin** [comment]
> Thanks for the feedback, @iProgramme! I am going to close this as a duplicate of #211.
> 
> If you are interested, we are working on a RFC (#231) that will allow participants to navigate among all the tabs a host has opened. If you have suggestions or comments, please do not hesitate to share them with us in that RFC. 🙇

i would like to share project folder to the joiner.
