### ISSUE TITLE
Tooltip should allow you to try again if initialization fails

### ISSUE THREAD

**Issue by 50Wliu** [atom/teletype#237]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

When initialization fails, the resulting tooltip should allow you to try again in case it was a temporary internet problem instead of making you disable and re-enable the package.
![teletype-initialization-failed-no-try-again-button](https://user-images.githubusercontent.com/2766036/32964489-b2d6188a-cbd3-11e7-9fe2-d0dda530732d.png)

### Steps to Reproduce

1. Turn off the interwebs
2. Try to start teletyping

**Expected behavior:** Teletype to error but allow me to retry

**Actual behavior:** Teletype errors and makes me reload the package

**Reproduces how often:** 100%

**Comment by jasonrudolph** [comment]
Closed by https://github.com/atom/teletype/pull/287.
