### ISSUE TITLE
Show error message in tooltip when initialization fails

### ISSUE THREAD

**Issue by 50Wliu** [atom/teletype#238]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

I don't think there's a reason to create a notification error when initialization fails because you'll always be going through the tooltip UI.  Perhaps the notification was added before the tooltip existed?  Either way, the tooltip should provide a copy of the error message.
![teletype-initialization-failed-no-try-again-button](https://user-images.githubusercontent.com/2766036/32964489-b2d6188a-cbd3-11e7-9fe2-d0dda530732d.png)

### Steps to Reproduce

1. Turn off the interwebs
2. Try to start teletyping

**Expected behavior:** Tooltip explains what the error is

**Actual behavior:** Tooltip contains a generic failure message

**Reproduces how often:** 100%

**Comment by rvermeiren** [comment]
Hi, 
I'm a student in last year in computer science at the UCL in Belgium and I want to make my first contribution to an open source project. I choose atom/teletype as it's one of my favorite tools for collaborative work and pair programming. 

Do you think it's an affordable fix for a beginner? I will work on a VM with the last LTS version of Ubuntu and use the development mode of Atom for testing my fix.

I have already read a lot of documentation on how to contribute to Atom.

I will very thankful if someone could help me if I have a problem.

Regards, 

Rémy

**Comment by nathansobo** [comment]
@rvermeiren Thanks for reaching out. I think it's worth a try. You need to understand how this package updates the contents of the tooltip and also look at where we present the notification. You'll also want to take a look at the existing tests to figure out how to add one to cover the new behavior. Good luck!

**Comment by jasonrudolph** [comment]
Closed by #309. Thanks, @rvermeiren. :bow:
