### ISSUE TITLE
Impersonating friend

### ISSUE THREAD

**Issue by laredo** [atom/teletype#239]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description
My friend shared his token which I promptly inserted in the Join field - However I had not signed in - 
From that moment on I was impersonating him, I had no option or way to remove that identity (I tried deleting atom, removing .atom folder, uninstalling plugin) 

After a reboot - still with my friends identity - I press the share button which produce a token that my friend was able to use - we shared a doc however we both were coming up with his identity - 

### Steps to Reproduce

1. Do not create identity toke
2. Take sharing token and insert it Join field - friend's identity is adopted

**Expected behavior:**

Would have liked the plugin to remind me that I first had to register

**Actual behavior:**

I took over his identity

**Reproduces how often:**

Not able to delete his identity - where is it kept?

### Versions

0.14 of Teletype 
1.22.1 for Atom

**Comment by nathansobo** [comment]
Hey @laredo, sorry about this. Check out #194 which is a very similar issue for some workarounds to the fact that we don't have an interface for signing out yet.
