### ISSUE TITLE
Allow Remote Users to Save

### ISSUE THREAD

**Issue by Jaco-Pretorius** [atom/teletype#240]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

Currently a remote user can modify the buffer but cannot save it.  This causes pain when remote pairing since the host has to remember to save the file after a change by the remote user.

### Steps to Reproduce

1. [Remote User Modifies the File]
2. [Remote User Invokes Save (Cmd+S)]

**Expected behavior:**

The File is Saved.

**Actual behavior:**

File Is not Saved.  Sadness.

**Reproduces how often:**

Always.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.10.0

macOS Sierra 10.12.6 (16G29)

**Comment by jasonrudolph** [comment]
Hi @Jaco-Pretorius! Thanks for opening this feature request. We've occasionally discussed the idea of allowing guests to trigger the file to be saved on the host's system, and it's helpful to have an issue where we can track it. :bow:

As we prioritize future work, we'll be looking at feature requests like this one to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors). In the meantime, if this is a feature that would make you smile each time you hit `command+s`, [adding a :+1: emoji reaction](https://github.com/blog/2119) to the [issue body](https://github.com/atom/teletype/issues/211#issue-274464843) is a great way to let us know. :smile:

**Comment by FrenchMasterSword** [comment]
It would be really useful for example simply with programs you cannot preview with any actual atom's packages
But of course it should be an _enabled_ (I just saw my first thumb's down here :(
Even though you're supposed to control people joining a conversation (might be hard with an id and so joining the feature request about **a list with people once connected with you**)

**Comment by as-cii** [comment]
We have provided a way for guests to save the host's buffer in #270, which will be published as part of the next Teletype release.

Thanks everyone for the feedback! 💯

**Comment by jasonrudolph** [comment]
> We have provided a way for guests to save the host's buffer in #270, which will be published as part of the next Teletype release.

Teletype 0.4.0 is now available and includes these improvements. 🚀
