### ISSUE TITLE
[Upgrade Experience] When Teletype is outdated it takes you to the Teletype package page with no options to upgrade

### ISSUE THREAD

**Issue by ungb** [atom/teletype#269]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Upgrade Experience] When Teletype is outdated it takes you to the Teletype package page with no options to upgrade

### Steps to Reproduce

1. Have a outdated version of Teletype
1. Click on the bottom right Teletype icon, Teletype says you need to upgrade and has a button that takes you to the package settings page
1. Click on the button that says `View Package Settings`

**Expected behavior:**

Ability to upgrade teletype.  

NOTE: from @jasonrudolph, this should be taking the user to `Settings Updates` page:

![image](https://user-images.githubusercontent.com/5624870/33851625-6389f282-de6c-11e7-960a-641a6b4d7a7f.png)

**Actual behavior:**

Takes you to package settings page for teletype but there's no option to upgrade.

**Reproduces how often:**

100%

See Gif of issue:
![upgradeexperience](https://user-images.githubusercontent.com/5624870/33851667-86e82186-de6c-11e7-906c-eec5d14866ca.gif)

**Comment by brysem** [comment]
Can confirm that I am experiencing the same bug as mentioned above. Manually uninstalling the package, searching for it from the list of packages and then reinstalling it fixed the issue.

**Comment by alexmylonas** [comment]
Same issue here

**Comment by as-cii** [comment]
The fix for this (#271) will be released as part of teletype v0.4.0, which will likely be published later this week. Thanks for the reports!
