### ISSUE TITLE
Add newly opened buffers when not following host

### ISSUE THREAD

**Issue by IbisLiven** [atom/teletype#274]
* [] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues
### Description

When a guest is following the host, any new buffers the host opens are added to the guest's workspace as a remote buffer. However if the guest isn't following the host (the guest is looking at different remote buffer, the host is following the guest instead, ...), any new buffers added by the host aren't added to the guest's workspace.

Could a change be made to add all the buffers the host opens while sharing a portal to every guest's workspace? or is this there a reason that this isn't the current behaviour? (i don't know if this is a feature or a bug, or just something overlooked)

### Steps to Reproduce
1. Host opens portal
2. guest joins portal
3. guest stops following host (opening another file, opening a different remote buffer from the one the host is looking at, host is following guest instead, ...)
5. host opens new buffer

**Expected behavior:**
When guest is following host: new buffers added by host are added to the guest's workspace 
(guest is switched to whatever host is looking at)
When guest it not following host: new buffers added by host are added to the guest's workspace 
(guest is not switched to whatever host is looking at)

**Actual behavior:**
When guest is following host: new buffers added by host are added to the guest's workspace 
(guest is switched to whatever host is looking at)
When guest it not following host: new buffers added by host are _not_ added to the guest's workspace 
(guest is not switched to whatever host is looking at)

**Reproduces how often:**
100%

### Versions
Atom: 1.23.0
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
Teletype 0.3.0

**Comment by jasonrudolph** [comment]
> Could a change be made to add all the buffers the host opens while sharing a portal to every guest's workspace? or is this there a reason that this isn't the current behaviour? (i don't know if this is a feature or a bug, or just something overlooked)

We're currently working on [RFC-001](https://github.com/atom/teletype/blob/7f6c15ad048c6431555ac7f841c64c21b1fa622e/doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md) (tracked in https://github.com/atom/teletype/issues/268) which will offer the ability for guests to use the [fuzzy-finder](https://github.com/atom/fuzzy-finder) to open any buffer that's present in the host's workspace. Our current thinking is that if you're not following the host, you probably don't want new tabs appearing in your editor every time the host opens a new buffer. Instead, you can re-follow the host to view/open their current buffer, and once RFC-001 is fully implemented, you'll also be able to use the fuzzy-finder to open any other buffers that the host has shared.

Once RFC-001 is implemented, if there are use cases you have in mind that aren't solved by following the host or by using the fuzzy finder, we'd love to hear about those use cases.

**Comment by CaptainJohnyAppleSeed** [comment]
I'm not sure if [RFC-001](https://github.com/atom/teletype/blob/master/doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md) completely handled this issue. Following the above reproduction steps, I was unable to use the fuzzy-finder to get the remote file. As is visible in the picture, the host (right) has a file open and shared that the guest cannot access.
![screen shot 2018-03-14 at 1 48 55 am](https://user-images.githubusercontent.com/31418316/37385310-e3a4321a-2729-11e8-892b-2bb43772c18d.png)

**Comment by jasonrudolph** [comment]
@CaptainJohnyAppleSeed: RFC-001's fuzzy-finder integration is dependent on [fuzzy-finder v1.8.0](https://github.com/atom/fuzzy-finder/releases/tag/v1.8.0) which will be included in Atom 1.26.

Keep an eye out for a beta release of Atom 1.26 soon.  :smile:

**Comment by jasonrudolph** [comment]
With the updates in teletype v0.10.0 and fuzzy-finder v1.8.0, we think we've addressed the needs described in this issue, so I'm going to close this out.

Thanks for opening this issue, @IbisLiven. :bow:
