### ISSUE TITLE
Avatar isn't in the correct pane in split pane view.

### ISSUE THREAD

**Issue by ungb** [atom/teletype#276]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

Avatar isn't in the correct pane in split view.

### Steps to Reproduce

1. Share a portal on Atom.
1. Guest should be following while host moves 1 buffer to the bottom.

**Expected behavior:**

Avatar is in the middle of the active buffer

**Actual behavior:**

Avatar shows up on middle of atom 
![image](https://user-images.githubusercontent.com/5624870/33914295-63a6d8a2-df52-11e7-9b11-c3897c93991c.png)

NOTE: if you split right it will show up in the right pane only and never the left one.
![image](https://user-images.githubusercontent.com/5624870/33914345-9db1400a-df52-11e7-8789-adcfc35c0701.png)

**Reproduces how often:**
100%

### Versions

commit 9b8a3cde53e246184ba260034a80ca750627a6dd

**Comment by jasonrudolph** [comment]
Thanks, @ungb. Right now, the avatar always appears on the right side of the Atom workspace, regardless of whether split panes are present in the workspace. However, I agree that this can sometimes be confusing when working with split panes, so we're looking into ways to remove that confusion.
