### ISSUE TITLE
Splitting remote pane causes avatar to disappear 

### ISSUE THREAD

**Issue by ungb** [atom/teletype#278]
### Description

Guest can't split remote pane and causes avatar to disappear

### Steps to Reproduce

1. Join a portal as a guest
2. On the shared buffer(not the tab)  click split down.

**Expected behavior:**

Avatar doesn't disappear.  

**Actual behavior:**

Opens an empty pane.  When you close the pane and go back to the remote buffer the avatar on the right is gone.  

![guestsplit](https://user-images.githubusercontent.com/5624870/33914756-8f8fa4d8-df54-11e7-959c-cd71a797a473.gif)

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.23.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

```

**Comment by jasonrudolph** [comment]
@ungb: Unless I'm misunderstanding, the split pane behavior and the disappearing avatars can be observed at the same time, but they're separate issues. I'll try to explain:

1. **Split panes** - In https://github.com/atom/teletype/pull/83, we intentionally added logic to prevent guests from splitting panes. In #83 we said:

    > We may revisit this decision in the future. Let's see what kind of feedback we get after the release, and we can assess the importance of split panes relative to other feature requests and the rest of the real-time collaboration roadmap.

    Can I talk you into removing the avatar-related aspects from this issue? (I'll try to explain why below.) Then, we can use this issue to track guests splitting panes as an enhancement request.

2. **Visibility of site position avatars** - Currently, we only show the site position avatars when the active pane item is an editor associated with a portal. From [RFC-001](https://github.com/atom/teletype/blob/7f6c15ad048c6431555ac7f841c64c21b1fa622e/doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md#following):

    > When viewing an editor associated with a portal, each participant sees the avatars for the other portal participants (just as they did prior to this RFC). As a host, when your active pane item is a local editor (i.e., an editor that you're sharing in your portal), the editor shows the avatars for the other portal participants. As a guest, when your active pane item is a remote editor (i.e., an editor that you're viewing from the host's portal), the editor shows the avatars for the other portal participants.

    In the gif above, the bottom pane is focused and empty. Since the focused item is _not_ an editor associated with a portal, the site position avatars are hidden. This behavior is not specific to split panes. If you were to focus another pane item (e.g., the settings view), that would also hide the site position avatars.

    If you think we should change this behavior, would you mind opening a separate issue describing the motivation for the change?

**Comment by ungb** [comment]
@jasonrudolph, the thing is if you close the bottom empty pane and the only pane open is the 1 buffer and no other tabs this can lead to a confusing experience.  The tab that is focused is the shared buffer.
![image](https://user-images.githubusercontent.com/5624870/33959644-04cf69d8-dffd-11e7-9c87-fd2c53f5cea7.png)


see below after closing the empty pane.  

If you try to split pane on the tab, this no-ops and nothing happens.  This only works if you right click inside the buffer and split pane there.
![image](https://user-images.githubusercontent.com/5624870/33959696-2d734940-dffd-11e7-8a3a-a1857c0f858d.png)

**Comment by ungb** [comment]
thanks @odoyle71 !  I can't repro the issue either on latest.  Closing!
