### ISSUE TITLE
Teletype initialization failed

### ISSUE THREAD

**Issue by mettaworldjon** [atom/teletype#296]
[already-filed]: https://github.com/atom/teletype/issues

Teletype error continues to pop up

**Comment by rsese** [comment]
Thanks for the report! Based on the issue title, I'm closing this as a duplicate of https://github.com/atom/teletype/issues/250.  If you have steps to reproduce this issue or any more details that might be helpful, please let us know in https://github.com/atom/teletype/issues/250.

For future issues, please fill out the issue template. The information requested in the template is super helpful for us when investigating issues.
