### ISSUE TITLE
Readonly mode

### ISSUE THREAD

**Issue by ungb** [atom/teletype#30]
I think it would be useful for presentation if people want to follow what's going on in Atom on their computer, but not allow anyone else to edit.  Also, having the ability to give people access to edit would be useful too

**Comment by JeffCohen** [comment]
FWIW: This would be super helpful for me when teaching, so that students see my code if they fall behind, but I don't want them to be able to change my code.

I'm willing to research the effort required to implement this if someone can point me in the right direction.

**Comment by jasonrudolph** [comment]
@JeffCohen: Thanks for the feedback. And a big thanks for the offer to help! :bow:

I can definitely see the benefit of a read-only mode for teaching. However, given that Teletype is focused on *collaborative* coding, read-only mode doesn't feel like a feature that is within the scope that we have have envisioned for Teletype. I worry that adding a read-only mode would complicate the user interface and increase the complexity of the code, thus increasing the cost of developing/maintaining Teletype's core functionality of collaborative coding.

If you think that a read-only mode should be within the scope of Teletype's vision and that there's a way to implement it where the benefits outweigh the costs, the first step would be for you to open an RFC describing the feature in detail. We don't yet have a template for RFCs, but you can use [RFC-001](https://github.com/atom/teletype/blob/37274d7bd22ce5cdc9f7ae1f0cdd72e1fa0442ec/doc/rfcs/001-allow-guests-to-open-multiple-remote-buffers.md) as an example. You'd want your RFC to include the same sections (*Summary*, *Motivation*, *Explanation*, *Drawbacks*, and *Unresolved Questions*) and roughly the same level of detail. You would then open a pull request that adds your RFC to [`doc/rfcs`](https://github.com/atom/teletype/tree/37274d7bd22ce5cdc9f7ae1f0cdd72e1fa0442ec/doc/rfcs), similar to the way that https://github.com/atom/teletype/pull/231 introduced RFC-001. I hope this helps. If you have any questions about putting together the RFC, just let us know.

**Comment by JeffCohen** [comment]
Got it, that explanation helps a lot.  I'll definitely ponder if there's a low-impact way to do this, and if so I'll definitely put an RFC together.  Thanks!
