### ISSUE TITLE
`TypeError: this.historyProvider.groupLastChanges` when joining portal

### ISSUE THREAD

**Issue by jasonrudolph** [atom/teletype#300]
### Description

Using the latest dev build of Atom, teletype throws an error when a participant attempts to join a portal.

### Steps to Reproduce

1. Host shares a portal
2. Guest joins the portal

**Expected behavior:**

Guest should be in the portal and able to collaboratively edit buffers with the host.

**Actual behavior:**

Guest sees error notification saying:

> Failed to join portal
>
> Attempting to join portal [REDACTED] failed with error: this.historyProvider.groupLastChanges is not a function

**Reproduces how often:**

100%

### Versions

```
$ atom --version
Atom    : 1.25.0-dev-dced608f4
Electron: 1.7.10
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-dev-dced608f4
python 2.7.10
git 2.15.1

$ apm list | grep teletype
├── teletype@0.5.0
```

**Comment by jasonrudolph** [comment]
@nathansobo @maxbrunsfeld: Does this seem like something that could be caused by the recent text-buffer changes on atom's master branch?

**Comment by nathansobo** [comment]
We added a new method to the default history provider that gets used in some circumstances. We'll need to update the package to support that method before shipping.

/cc @maxbrunsfeld @as-cii
