### ISSUE TITLE
Release a changelog at every new update

### ISSUE THREAD

**Issue by Nicryc** [atom/teletype#303]
Hello,
It would be nice to release a changelog every time a new version comes out :)

**Comment by xmsid** [comment]
This would be really useful instead of me going through the GitHub page trying to know what's this 0.6.0 update is about.

**Comment by jasonrudolph** [comment]
@Nicryc @xmsid: Thanks for sharing this feedback. 💟  I'm a big fan of changelogs as well, and I've often wanted to see each package's release notes in Atom when I'm updating packages.

> This would be really useful instead of me going through the GitHub page trying to know what's this 0.6.0 update is about.

@xmsid: Can you tell me where you looked for release notes on GitHub? I can probably guess :wink:, but I wanted to ask to be sure. 😇  If we invest time in putting together release notes, I wanna make sure we're putting them somewhere that people are likely to look for them. :smile:

**Comment by xmsid** [comment]
@jasonrudolph: I looked in README.md firstly then i went through the closed enhancement issues looking for features that wasn't in the 0.5.0 update, I would recommend putting a changelog in the README.md or putting CHANGELOG.md file if you want to keep the README.md clean.

**Comment by jasonrudolph** [comment]
> I looked in README.md firstly then i went through the closed enhancement issues looking for features that wasn't in the 0.5.0 update

@xmsid: I'm glad I asked. My guess was totally wrong. 😬  I would've guessed that folks look at the [releases page](https://github.com/atom/teletype/releases).

Thanks again for the suggestion. :bow:

**Comment by returnlytom** [comment]
@jasonrudolph After looking for `CHANGELOG.md`, I then checked the releases page, then closed PRs. So, your guess was correct after all :)

**Comment by Nicryc** [comment]
Personally, my first thought was to check the releases page :x
