### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by drem-darios** [atom/teletype#318]
Hi, after updating to 0.7.0 I am prompted to Restart Teletype. On every restart I get the same Teletype Initialization failed error. The developer console actually reports a 304 status code but here are the diagnostics:

### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version
Status Code: 200
Body: R<n�����
���

```
### Versions

**Teletype version**: v0.7.0
**Atom version**: 1.23.3
**Platform**: darwin

**Comment by jasonrudolph** [comment]
@drem-darios: Thanks for opening this issue, and thanks for pointing out the `304` response code! :bow:

After seeing that response code, I noticed that Teletype is making [conditional requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) to `GET /protocol-version`, and somehow your Atom instance has cached a problematic response. We can see that teletype-server returns an Etag header in the response:

```
$ curl -i https://api.teletype.atom.io/protocol-version

HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 13
Etag: W/"d-MaS+LUY/qwRdJ3/Z0vJ+lNsXnE8"                     <=======================
Date: Tue, 06 Feb 2018 19:18:57 GMT
Via: 1.1 vegur

{"version":6}
```

And using my local instance of teletype-server, I verified that incoming requests use the Etag to make conditional requests using the `if-none-match` header:

```
If-none-match: W/"d-MaS+LUY/qwRdJ3/Z0vJ+lNsXnE8"
```

Given that it's extremely cheap for the server to build the response to this endpoint, and given that the response is so small, I don't think there's any benefit in supporting conditional requests for this endpoint. Instead, I think the server should omit the Etag response header and should always return the full JSON response body for this endpoint.

@as-cii: What do you think?

---

Refs: https://github.com/atom/teletype/issues/266

**Comment by jasonrudolph** [comment]
@drem-darios: When you have a moment, can you try disabling the cache and to see if that changes the behavior you're seeing?

1. Open the developer console
2. Click the "Network" tab
3. Click the "Disable cache" checkbox [[screenshot](https://user-images.githubusercontent.com/2988/35883290-c10f7246-0b54-11e8-8b07-c3f86533f2ce.png)]
4. With the developer console still open, click the "Restart Teletype" button

**Comment by as-cii** [comment]
That seems reasonable, @jasonrudolph, although I am unclear on why the server replied with that nonsense response. I assume this could happen on other endpoints as well, so I wonder if there is something wrong with either Heroku, the express application or teletype-client's REST gateway.

**Comment by jasonrudolph** [comment]
We've deployed the changes in https://github.com/atom/teletype-server/pull/47, and I'm hopeful that those changes will reduce or eliminate 🤞 these package initialization errors. With that in mind, I'm going to close this issue. If anyone is still consistently seeing package initialization errors, please let us know.
