### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by aminnaggar** [atom/teletype#320]
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version
Status Code: 200
Body: �B���

```
### Versions

**Teletype version**: v0.7.0
**Atom version**: 1.23.3
**Platform**: darwin

-----

from the console

```
WebSocket connection to 'wss://ws-mt1.pusher.com/app/MY_PUSHER_KEY?protocol=7&client=js&version=4.2.2&flash=false' failed: WebSocket is closed before the connection is established.
```

**Comment by jasonrudolph** [comment]
@aminnaggar: Thank you for taking the time to report this error. We're looking into options for preventing this issue. In the meantime, would you mind trying the steps in https://github.com/atom/teletype/issues/318#issuecomment-363559779? That might resolve the issue for you.

**Comment by aminnaggar** [comment]
Wish I'd seen your comment sooner @jasonrudolph , I restarted my computer for the second time, and now it seems to be working again. I'll close this until it happens again. 

Thanks again, Cheers.
