### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by AbdullahHadi1** [atom/teletype#325]
### Diagnostics

```
Request: GET https://api.teletype.atom.ioREDACTED
NEW MESSAGES
/protocol-version

```
### Versions

**Teletype version**: v0.7.0
**Atom version**: 1.23.3
**Platform**: win32

**Comment by rsese** [comment]
I'll go ahead and close this as a duplicate of https://github.com/atom/teletype/issues/318 for now but we can re-open if necessary.
