### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by lilskrt** [atom/teletype#333]
### Diagnostics

```
Request: GET https://api.teletype.atom.io/protocol-version

```
### Versions

**Teletype version**: v0.9.0
**Atom version**: 1.24.0
**Platform**: darwin

**Comment by rsese** [comment]
Thanks for reporting!  As mentioned by Jason in https://github.com/atom/teletype/issues/320#issuecomment-364241144, the team is investigating this error but in the meantime, can you give the steps detailed in https://github.com/atom/teletype/issues/318#issuecomment-363559779 a try and let us know if that resolves the error for you?   We'll go ahead and close as a duplicate for now.
