### ISSUE TITLE
Uncaught 'client' is not a recognized auth transport

### ISSUE THREAD

**Issue by OriginalAse** [atom/teletype#334]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.9.0

### Stack Trace

Uncaught 'client' is not a recognized auth transport

```
At C:\Users\venup\.atom\packages\teletype\node_modules\pusher-js\dist\web\pusher.js:3023

undefined
```

### Commands

```
     -3:51.1.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -3:40 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -3:26.2.0 AtomPair:join pairing session (ul.list-inline.tab-bar.inset-panel)
     -3:19.9.0 core:paste (input.hidden-input)
     -3:18.7.0 core:confirm (input.hidden-input)
     -2:56.4.0 command-palette:toggle (input.hidden-input)
  2x -2:50.4.0 core:backspace (input.hidden-input)
     -2:41.7.0 AtomPair:join pairing session (input.hidden-input)
     -2:40.2.0 core:paste (input.hidden-input)
     -2:36.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-pair 2.0.13 
autoclose-html 0.23.0 
teletype 0.9.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Do you have steps to reproduce or do you remember what you were doing when you saw the error?

**Comment by OriginalAse** [comment]
I figured out why it wasn't working, the other person's school just blocked a lot of thinhs

**Comment by OriginalAse** [comment]
> apm install atom-pair

> apm install autoclose-html

> apm install teletype

**Comment by OriginalAse** [comment]
`<html class="nav navbar nav" style="color: Chucknorris"></html>`

**Comment by rsese** [comment]
> I figured out why it wasn't working, the other person's school just blocked a lot of thinhs

Thanks for sharing your findings :+1:

Not sure if y'all want to track the error itself @jasonrudolph @as-cii but I'll go ahead and close for now.

**Comment by Cawet** [comment]
Hello, 
sorry to re open  but I've got same error. I'm on a regular network, on Manjaro. 
Teletype alone work nicely.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.12
**OS**: "Manjaro Linux"
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.4


### Stack Trace

Uncaught 'client' is not a recognized auth transport

```
At /home/cawet/.atom/packages/teletype/node_modules/pusher-js/dist/web/pusher.js:3053

undefined
```

### Commands

```
  2x -9:57.1.0 core:move-up (input.hidden-input)
  5x -7:56.8.0 core:backspace (input.hidden-input)
     -6:28.5.0 settings-view:open (input.hidden-input)
     -5:46.8.0 command-palette:toggle (div.package-detail)
     -5:43.7.0 AtomPair:start new pairing session (div.package-detail)
     -1:28.2.0 command-palette:toggle (atom-pane.pane.active)
     -1:24.1.0 AtomPair:start new pairing session (atom-pane.pane.active)
```

``` 

atom-pair  2.0.23
teletype 0.13.0 
atom 1.43.0
Electron 4.2.12
Chrome 69.0.3497.128
Node : v10.11.0

```
