### ISSUE TITLE
[UX] Avatar with border

### ISSUE THREAD

**Issue by WaKeMaTTa** [atom/teletype#338]
Can we make a border to the avatars with the colour of the cursor? (this allow you to identify each person easier).

**Comment by jasonrudolph** [comment]
@WaKeMaTTa: This is indeed something we'd like to do, but we hadn't yet opened an issue for it. Thanks for opening an issue. :smile:

@simurai sketched out a mockup in https://github.com/atom/teletype/issues/286#issuecomment-352384609, and I'll inline it here for easy reference:

![](https://user-images.githubusercontent.com/378023/34096415-8aa85ad2-e418-11e7-84f3-2a78c04ede17.png)

**Comment by simurai** [comment]
Another option to make the "who is typing" more clear, have these name "fags" attached to cursors, like in Google Docs:

![who](https://user-images.githubusercontent.com/378023/37325142-f6276d9e-26cf-11e8-929a-9fe457504843.png)

And maybe even take over Git Diff and color the gutter border and background with a user's color:

![who 2](https://user-images.githubusercontent.com/378023/37325192-2beb67aa-26d0-11e8-8c37-637c159427ab.png)

When starting to follow someone, you would see what they have been typing so far and can understand what they are doing better. The colored background might get muddy with a selection, cursor-line and search results etc.
