### ISSUE TITLE
Icon not displayed correctly when following another user

### ISSUE THREAD

**Issue by as-cii** [atom/teletype#345]
After the improvements introduced in #332, it seems like the little "link icon" displayed next to the user I am following isn't being rendered correctly anymore:

![screen shot 2018-03-20 at 09 07 33](https://user-images.githubusercontent.com/482957/37642646-3b54ef7e-2c1e-11e8-819e-c7b6eb9bd29c.png)

I assume the icon should go in front of the blue background, but for some reason I think `z-index` isn't working correctly. I have noticed we're using pseudo elements to represent the background and the icon link:

![screen shot 2018-03-20 at 09 08 06](https://user-images.githubusercontent.com/482957/37642705-78bd018a-2c1e-11e8-8186-855395817cd4.png)

Maybe there's a way of doing everything in the same element or swap the rendering order somehow without using `z-index` (or maybe by creating a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context))?.

This is the configuration I am using:

* UI theme: One Dark UI
* Syntax theme: One Dark Syntax
* Atom version: 1.27.0-dev-079a43f7b (but I can reproduce on 1.25 stable too)
* Teletype version: 0.10.0
* Relevant personal style sheet configuration: none
* Relevant configuration settings: none
* Can reproduce in safe mode: yes

/cc: @simurai @jasonrudolph

**Comment by jasonrudolph** [comment]
Thanks for logging this, @as-cii. 

@simurai: I haven't been able to reproduce this issue. Can you think of anything that might be causing this?
