### ISSUE TITLE
Problem with Teletype

### ISSUE THREAD

**Issue by RANKKY** [atom/teletype#347]
Me and my friend are working on a website together via teletype. My problem is, that I can't open the file in my browser (firefox). How does that work?
Thanks for your help

**Comment by rsese** [comment]
Thanks for reaching out - it sounds like you're having a general issue viewing your website files in Firefox and you're not having a specific issue with Teletype?

For general questions, feel free to post on our message board (you can @ mention me there if you'd like):

https://discuss.atom.io/

I'll go ahead and close but if I'm mis-understanding and you're having trouble using Teletype, please let me know.
