### ISSUE TITLE
Lines where coworker's profile picture shown not clickable

### ISSUE THREAD

**Issue by mbergen** [atom/teletype#362]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

When working with one guest, the lines in whose on the right side the profile picture of the guest is shown are not clickable, so you can't place the cursor with your mouse/touchpad.
Appears also on the guest's side.

### Steps to Reproduce

1. Open a portal
2. let at least one guest join
3. try to place the cursor by mouse in the lines where on the side the picture of the coworker is shown

**Expected behavior:**

Cursor can be placed by mouse, like in every other line

**Actual behavior:**

Cursor is not placed

**Reproduces how often:**

100% since last update, but only have one other client to test with

### Versions
atom --version
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64

OS: Windows 10 Pro 1709

**Comment by mbergen** [comment]
Just a small annotation to your comment @jasonrudolph  :
line 40 is already where clicking does not cause the cursor to appear, whereas clicking on line 42 should work. (at least it does for me)

**Comment by simurai** [comment]
@mbergen Great catch. 👌 

Looks like the wrapper for the avatars blocks clicks.

![image](https://user-images.githubusercontent.com/378023/38720107-e4fe4de4-3f2f-11e8-857b-995d0e00a627.png)

We should be able to only make avatars clickable.
