### ISSUE TITLE
Unable to install teletype in atom

### ISSUE THREAD

**Issue by deivisleung** [atom/teletype#364]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. Installing Packages in item.

Installing “teletype@0.12.2” failed.Hide output…

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\deivi_000\\AppData\\Local\\atom\\app-1.25.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\deivi_000\\AppData\\Local\\atom\\app-1.25.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\deivi_000\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\deivi_000\\.atom\\.apmrc" "install" "C:\\Users\\DEIVI_~1\\AppData\\Local\\Temp\\d-118317-11344-1ocufrx.k6mfq4obt9\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\deivi_000\.atom\.apm\event-kit\2.4.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\deivi_000\.atom\.apm\event-kit\2.4.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DEIVI_~1\AppData\Local\Temp\apm-install-dir-118317-11344-19p9e5n.1owvfs9k9\npm-debug.log

**Comment by Ben3eeE** [comment]
Thanks for the report!

Can you try resetting to factory defaults before trying to install teletype to see if this resolves the issue? https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

xref: https://github.com/atom/atom-space-pen-views/issues/22 which has a similar error message that was resolved by resetting to factory defaults.

**Comment by mariosumd** [comment]
This is happening to me right now. Just updated to atom 1.26.1, and teletype couldn't update, so I tried to reinstall, and now I can't install it. My logs are different, tho:

```
Installing “teletype@0.13.2” failed.Hide output…
C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi
`-- (empty)


npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\package.json'
npm WARN apm-install-dir-11842-6444-fqosv.4duxy4aemi No description
npm WARN apm-install-dir-11842-6444-fqosv.4duxy4aemi No repository field.
npm WARN apm-install-dir-11842-6444-fqosv.4duxy4aemi No README data
npm WARN apm-install-dir-11842-6444-fqosv.4duxy4aemi No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\MarioSumD\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\MarioSumD\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\MarioSumD\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\MarioSumD\\.atom\\.apmrc" "install" "C:\\Users\\MARIOS~1\\AppData\\Local\\Temp\\d-11842-6444-1p60uop.jr043d6lxr\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\.staging\event-kit-ed52b00b
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\.staging\event-kit-ed52b00b' -> 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\teletype\node_modules\event-kit'
npm ERR!     at destStatted (C:\Users\MarioSumD\AppData\Local\atom\app-1.26.1\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\MarioSumD\AppData\Local\atom\app-1.26.1\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\.staging\event-kit-ed52b00b' -> 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\teletype\node_modules\event-kit'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\.staging\event-kit-ed52b00b' -> 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\teletype\node_modules\event-kit'
npm ERR!     at destStatted (C:\Users\MarioSumD\AppData\Local\atom\app-1.26.1\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\MarioSumD\AppData\Local\atom\app-1.26.1\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\.staging\event-kit-ed52b00b' -> 'C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\node_modules\teletype\node_modules\event-kit'
npm ERR!     at Error (native) parent: 'teletype' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MARIOS~1\AppData\Local\Temp\apm-install-dir-11842-6444-fqosv.4duxy4aemi\npm-debug.log
npm ERR! code 1
```

**Comment by rsese** [comment]
@mariosumd your error looks like https://github.com/atom/apm/issues/778 - can you try the suggestion in https://github.com/atom/apm/issues/778#issuecomment-375455719 and see if disabling any antivirus program on your computer helps?

And thanks again for your issue @deivisleung!

We haven't received a response to our question in this comment https://github.com/atom/teletype/issues/364#issuecomment-382159684. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
