### ISSUE TITLE
Failed to authenticate to teletype

### ISSUE THREAD

**Issue by NikhilDoWhile** [atom/teletype#367]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

Teletype is not working, failing to authenticate token. Even on generating the token again same error pop up.

### Steps to Reproduce

1. Open Atom 
2. Error pops up: Failed to authenticate to teletype
3. Signing in Failed with error: unexpected response 
4. Login again to generate token
5. Enter the new token, same error pops up again

**Expected behavior:**

I expected that on entering the newly generated token it will work.

**Actual behavior:**

Authentication fails.

**Reproduces how often:**

Tried to generate token multiple times, every time same error.

### Versions

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 3.6.3
git 1.9.4.msysgit.2
visual studio

OS: Windows 10, version 1709
Teletype: 0.13.1

### Additional Information

Screenshot of error and console result:
[1](https://imgur.com/g2yy9g9)
[2](https://imgur.com/bh8T6Pm)
[3](https://imgur.com/a/uy5VBaU)

**Comment by rsese** [comment]
Thanks for the report!  From your screenshot I also see a "That token does not appear to be valid" error message - not sure if that's separate or related but when you copy/paste the token can you double check that the token is the same in case there's some random issue with the copy/paste?

Also, if you follow Jason suggestion in https://github.com/atom/teletype/issues/366#issuecomment-383099249, does that make a difference?

Lastly, just to clarify this from your repro steps:

> 1. Open Atom
> 2. Error pops up: Failed to authenticate to teletype

So the error is popping up right after starting Atom and not when you specifically try to share/join a portal?

**Comment by NikhilDoWhile** [comment]
> "That token does not appear to be valid" error message

When I visit https://teletype.atom.io/login , Copy the token, Paste it and Click on sign in (in atom). 
Then both of these error pop up: 

-  The Token does not appear to be valid, 
-  Failed to authenticate to teletype.  

> when you copy/paste the token can you double check that the token is the same

Yes I did check the token word by word multiple times.

> Also, if you follow Jason suggestion in #366 (comment), does that make a difference?

No, same error is coming with this method also
 
>So the error is popping up right after starting Atom and not when you specifically try to share/join a portal?

I was using Atom yesterday too, but there were no error at all. There were two package updates in Atom today, one of which was of Teletype. Only after that this error is coming. 
I think after the update have to sign in again and since then this issue is there. The error is popping as soon as I enter the token to log-in.

**Comment by jasonrudolph** [comment]
@NikhilDoWhile: Can you share a screenshot of the response to the `identity` request? 

![bh8t6pm_-_imgur](https://user-images.githubusercontent.com/2988/39371600-2ab3e462-4a10-11e8-967c-9cb737d67c14.png)

The error message indicates that Teletype got an unexpected response, and seeing the content of the response might help us diagnose the issue.

**Comment by NikhilDoWhile** [comment]
Response to ice-servers:

`� ���W�^�.O0�D��O��https://raw.githubusercontent.com/jas-chen/atom-live-server/master/doc/demo.gif":"c7b5d1b69ea951fbc1a893803f42951a847714803083cafc1be7eefcb944aef6","credential":"MTeLeQB3yOqL/bhTTzTHaudSE3Izp4jbazIagFhYk5c="}]`                                                                       

Response to identity:
<img width="957" alt="identity" src="https://user-images.githubusercontent.com/9911561/39378101-014f8bf2-4a75-11e8-8e28-ebf066ebfa1b.PNG">

**Comment by jasonrudolph** [comment]
Thanks, @NikhilDoWhile. That response from `/ice-servers` looks like it might be the source of the problem. Can you try doing this to gather a bit more info for us? 

1. Open the `Network` tab so that it shows all network requests. (See screenshot below.)
2. Reload Atom. (In the Command Palette, run the `Window: Reload` command.)
3. Click the Teletype icon in the status bar.
4. Enter your token and click sign in.
5. Take a screenshot of the network requests (like the screenshot below) and post a reply here that includes the screenshot.

![screen shot 2018-04-27 at 15 24 59 pm](https://user-images.githubusercontent.com/2988/39381342-c9f34404-4a2f-11e8-94f3-41b56c4addc5.png)

Thanks for helping us diagnose this issue. :bow:

**Comment by NikhilDoWhile** [comment]
Identity (Possible error): 
<img width="960" alt="1" src="https://user-images.githubusercontent.com/9911561/39382913-e16a341c-4a84-11e8-9573-f9869c9b8b64.PNG">

Identity (Possible error): 
<img width="841" alt="4" src="https://user-images.githubusercontent.com/9911561/39383271-49cadac4-4a86-11e8-8ad1-cec24a1d4f16.PNG">


Identity:
<img width="845" alt="2" src="https://user-images.githubusercontent.com/9911561/39383035-59e1a54c-4a85-11e8-9dbf-71e943483b09.PNG">


Ice-servers:
`� ���W�^�.O0�D��O��https://raw.githubusercontent.com/jas-chen/atom-live-server/master/doc/demo.gif":"c7b5d1b69ea951fbc1a893803f42951a847714803083cafc1be7eefcb944aef6","credential":"MTeLeQB3yOqL/bhTTzTHaudSE3Izp4jbazIagFhYk5c="}]`

**Comment by NikhilDoWhile** [comment]
As of now it has started working again, I tried logging in today and it's working for now.
