### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by billymoon** [atom/teletype#374]
Would be very cool if I could send a url to a friend and for them to get a web page with codemirror or the like from which they can edit as if they were using atom editor.

... basically allow access to non atom users.

**Comment by Arcanemagus** [comment]
This repository is _specifically_ the Atom package implementing the Teletype protocol.

I think you are likely looking for [teletype-client](https://github.com/atom/teletype-client), the goal of which is to provide a library to talk the Teletype protocol in an editor agnostic manner, allowing other editors to implement it and work with an Atom instance on a document. If that doesn't fill your needs either file an issue there or look over the [teletype-crdt](https://github.com/atom/teletype-crdt) and [teletype-server](https://github.com/atom/teletype-server) repositories for how to implement it in your own language/application.

Thanks for taking the time to file an issue!
