### ISSUE TITLE
I cannot see what the other files are from other people in the portal. 

### ISSUE THREAD

**Issue by nithyam16122** [atom/teletype#376]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

[What did you expect to happen?]

**Actual behavior:**

[What actually happened instead?]

**Reproduces how often:**

[What percentage of the time does this happen?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

**Comment by nithyam16122** [comment]
I expect to see what the other people in the portal are doing and what files they have opened.

**Comment by rsese** [comment]
Thanks for reaching out - it's an interesting idea but there isn't enough information here for us to consider the issue as is.  We'll close for now but feel free to open a new issue (and use the issue template as much as possible) or edit the issue body here and add more details about what you're picturing and why it would useful.
