### ISSUE TITLE
Issue Installing Atom Teletype package.json file

### ISSUE THREAD

**Issue by sahil48** [atom/teletype#390]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

I attempt to install teletype through the following methods:

- Atom
- Atom in Safe Mode
- APM through command line
- APM through command line with administrative privaleges

I receive an error that there is an error with a package.json file that is not a bug in apm, and to contact author of the package.

### Steps to Reproduce

1. Attempt to install the package Teletype
2. Receive Error
3. Try to find the log file, but cannot find it

**Expected behavior:**

[What did you expect to happen?]
I expected Teletype would install.

**Actual behavior:**

Output from Atom/apm (with my user name replaced with %USER% characters) shown below:

```
Installing “teletype@0.13.3” failed.Hide output…

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\%USER%\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\%USER%\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\%USER%\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\%USER%\\.atom\\.apmrc" "install" "C:\\Users\\%USER%\\AppData\\Local\\Temp\\d-118522-79380-1r7ey4j.emx67s0pb9\\package.tgz" "--runtime=electron" "--target=2.0.3" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\%USER%\.atom\.apm\xmlhttprequest\1.8.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\%USER%\.atom\.apm\xmlhttprequest\1.8.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\%USER%\AppData\Local\Temp\apm-install-dir-118522-79380-17tt5by.q5v7ycik9\npm-debug.log
```

**Reproduces how often:**

always when attempting to install teletype

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

atom --version
Atom: 1.28.0
Electron: 2.0.3
Chrome: 61.0.3163.100
Node: 8.9.3

apm --version
apm 1.19.0
npm 3.10.10
node 6.9.5
atom 1.28.0
python
git 2.17.1.windows.1
visual studio 2015

Operating System: Microsoft Windows [Version 10.0.17134.112]

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

C:\Users\%USER%\AppData\Local\Temp\apm-install-dir-118522-79380-17tt5by.q5v7ycik9\npm-debug.log

The above file is unavailable after installation. I cannot even find the apm-install-dir... folder.

**Comment by rsese** [comment]
Thanks for the report - this looks pretty similar to https://github.com/atom/apm/issues/593.  Can you try deleting `C:\Users\%USER%\.atom\.apm\xmlhttprequest` and then try reinstalling Teletype?

**Comment by sahil48** [comment]
That fixed it! Thank you so much. This was driving me crazy for months. I can finally install Hydrogen too. It's kind of odd that apm can't determine that it's an apm issue.
