### ISSUE TITLE
cant connect using teltype to my peers 

### ISSUE THREAD

**Issue by pankaj-sharma96277** [atom/teletype#397]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

[What did you expect to happen?]

**Actual behavior:**

[What actually happened instead?]

**Reproduces how often:**

[What percentage of the time does this happen?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by pankaj-sharma96277** [comment]
sir, the real issue is I can't see my friends document on my atom editor
meanwhile he can see mine

**Comment by rsese** [comment]
If you can fill out the issue template details in the issue body with more details or open a new issue with the template filled out, we can take a look.

Please share steps to reproduce, what version of Atom you're running, what operating system, screenshots or GIFs - anything that will help us understand what you're seeing.   Describing what you mean when you say "I can't see my friends document on my atom editor" would be helpful too - what exactly do you see?
