### ISSUE TITLE
URL shortener

### ISSUE THREAD

**Issue by tigoe** [atom/teletype#402]
TeleType is great, and a useful tool for sharing code with students in a classroom, but the URLs for sharing are a real problem for users who are low-vision or have typing limits. Might be good to add an URL shortener so that users could customize the link to something memorable. I assume names are meant to be temporary, so statistically improbable phrases like conspicuous-pumpkin-rider could work as well, and are more memorable.

**Comment by rsese** [comment]
Thanks for the suggestion!  I think I understand what you're describing here but just to clarify, the use case you're describing is where people don't have the ability to easily share URLs with others so it can just be copy/pasted (e.g. via Slack) and people have to type out URLs manually?

Also, there's an existing feature request for persistent portals: https://github.com/atom/teletype/issues/284.  Would this be enough for the situation you have in mind?

**Comment by tigoe** [comment]
That is a use case, yes. I was thinking more specifically of blind users in a classroom, where a speakable and memorable URL is more critical. Also, having to depend on another tool, like Slack, limits the accessibility. It assumes Slack has good usability for those users as well.

**Comment by Aerijo** [comment]
What about emailing it then? Typing out URLs manually is a very annoying thing to do in general, and I always thought it would be great if the teacher could just send us the link in a group email.

**Comment by tigoe** [comment]
OK, no worries .Let's close the issue.
