### ISSUE TITLE
Allow invitees to edit other files other than the one the host is in the same project folder

### ISSUE THREAD

**Issue by MawiraIke** [atom/teletype#435]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

I invited a colleague of mine to join my work space and edit a specific file while i worked on another file in the same project but for some reason if i leave the view of the file, the colleague also leaves the view and sees the other file that i am viewing. All attempts failed and all efforts to fix him to the file fail. 

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

80%

### Versions

Atom    : 1.34.0
Electron: 2.0.16
OS: Windows 10 Professional

**Comment by rsese** [comment]
Thanks for reaching out!  

> if i leave the view of the file, the colleague also leaves the view and sees the other file that i am viewing. All attempts failed and all efforts to fix him to the file fail.

Just to clarify, your colleague isn't having trouble switching to any other files you opened, you just don't want them to automatically switch to whatever file you view?

Also, have they clicked on your avatar to unfollow you?  Your avatar shouldn't have the little chain icon on it from their view.
