### ISSUE TITLE
Fix renderer crash issue in PortalListComponent test in Electron 3.0

### ISSUE THREAD

**Issue by daviwil** [atom/teletype#438]
### Description

It seems that there's an issue with `window.fetch` in Atom, built on Electron 3.0, which causes a renderer process crash in the ["PortalListComponent initialization"](https://github.com/atom/teletype/blob/23fa5c056e2bb1c86a0521964f2df1393d243143/test/portal-list-component.test.js#L36) test when `TeletypeClient.initialize` [gets called](https://github.com/atom/teletype/blob/23fa5c056e2bb1c86a0521964f2df1393d243143/test/portal-list-component.test.js#L256).  I've tracked this down to the usage of `window.fetch` inside of `teletype-client`'s [`RestGateway.fetch`](https://github.com/atom/teletype-client/blob/09f3fea46967daeee998451024fafd7b581c724a/lib/rest-gateway.js#L33) method.  This problem doesn't occur when Atom is built with Electron 2.0 and below.

Strangely, I'm able to use Teletype with no issues inside of Atom so I suspect that this might be an issue with how Teletype's tests are configured and executed.

### Steps to Reproduce

1. Download an Atom Dev build or build it from `master`
2. Follow steps in [README.md](https://github.com/atom/teletype#running-locally) to clone Teletype package and set up test DB
3. Run `atom --test test` in the `teletype` repo folder (use the Atom Dev build for this)
4. Observe renderer process crash at the "PortalListComponent initialization" test

**Comment by rafeca** [comment]
Fixed by https://github.com/atom/teletype/pull/453
