### ISSUE TITLE
this token does not appear to be valid

### ISSUE THREAD

**Issue by LigaFrost** [atom/teletype#440]
When i try to get access to the teletype i crash into an error "this token does not appear to be valid". And Atom's notification is "Failed to authenticate to teletype. Signing in failed with error Unexpected response".
![image](https://user-images.githubusercontent.com/33072840/53265058-463c8b00-36ee-11e9-8ef7-ca02ae4bc86c.png)

Description

I tried to search for that issue and to make simpler helping, here are screenshots of the responses. 
![image](https://user-images.githubusercontent.com/33072840/53265246-d4b10c80-36ee-11e9-8e3a-58aade9ace5e.png)

and ice-servers:
��Q���N�W�.e(��N���}��https://cloud.githubusercontent.com/assets/16760489/19395499/69bbb780-922d-11e6-9779-2b8327027ea5.png�#�
�;])�.�puVT�
�G:F�https://chrome-devtools-frontend.appspot.com/serve_file/@7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33/product_registry_impl/product_registry_impl_module.js(���^+b�.2DH�&ЁShttps://travis-ci.org/AtomLinter/l 

Steps to Reproduce

1. Tap on teletype icon
2. Go to https://teletype.atom.io/login
3. Login via GitHub, get and copy token
4. Put token in the teletype's field

Versions

Teletype is the latest's 0.13.3 version.

Hope for helping.

**Comment by rsese** [comment]
Thanks for the report - just to confirm if this is specific to Teletype, do you have a similar problem if you try to login to the GitHub tab?  Also, can you share what operating system you're running and copy/paste the output of `atom -v`?

**Comment by LigaFrost** [comment]
Thanks for the recent answer. 
The OS os Windows 10. 
Here is the output of the atom -v:
![image](https://user-images.githubusercontent.com/33072840/53272893-8bb78300-3703-11e9-89e1-7dfeddd601b1.png)

As for GitHub, the access is granted.
![image](https://user-images.githubusercontent.com/33072840/53274071-fddd9700-3706-11e9-8799-02f85d6045b5.png)

**Comment by rsese** [comment]
Were you able to get past that error @LigaFrost?  

Sorry and just to clarify about the "GitHub tab", I meant in Atom for the GitHub package.  In the command palette, it's the "GitHub: Toggle GitHub Tab" command and like Teletype, will have you get a token from atom.io when you have a repository open with a github.com remote.

**Comment by LigaFrost** [comment]
Now all works perfectly. As for solution: I did nothing to fix the problem. It just started working next day (like in issue #367). GitHub was working, if it could help you. Anyway thanks for answers:)
