### ISSUE TITLE
Can't push code with github in atom

### ISSUE THREAD

**Issue by souhagaa** [atom/teletype#459]
Whenever I try to push code with github it shows this error:
git: 'credential-' is not a git command. See 'git --help'.
The most similar command is
	credential
remote: Permission to souhagaa/log_analysis.git **denied to souha-echelon**.
fatal: unable to access 'https://github.com/souhagaa/log_analysis.git/': The requested URL returned error: 403
It says permission denied to "souha-echelon" which is not my username on github I guess I may have entered it wrongly, and I can't figure out how to change it from atom. I can push code from the terminal quite fine.

I tried uninstalling atom and deleting configuration files but still it didn't log out from github.
I even tried to clear saved state by executing $atom --clear-window-state and also tried resetting to Factory Defaults with $mv ~/.atom ~/.atom-backup
Can anyone tell me what to do?
![Capture d’écran de 2019-06-18 16-38-59](https://user-images.githubusercontent.com/34986304/59693802-c62fb900-91e7-11e9-8dc1-ace77690de8c.png)

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/github repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Also, please fill out the issue template in the new issue, the information in the template is super helpful for us when triaging issues.

Thanks for meeting us half way 👍
