### ISSUE TITLE
It goes slow...

### ISSUE THREAD

**Issue by tomasmparra** [atom/teletype#468]
The Teletype's installation goes SUPER slow!

Ty guys! you rock anyway!

**Comment by rsese** [comment]
Thanks for the feedback and the kind words!

Not sure what kind of install time you're seeing, is it minutes or tens of minutes?  Filling out the issue template is super helpful for us so please keep that in mind for future issues.

I think the install time could vary based on things like your location, what kind of computer you have, how you connect to the internet, etc.  But I'd also guess that you probably see similar install times for other packages as well so this isn't specific to Teletype?  In any case, it sounds like besides the wait, you have Teletype installed and running so we'll go ahead and close this out and share your feedback with the other maintainers.

Thanks again :bow:
