### ISSUE TITLE
Package Initialization

### ISSUE THREAD

**Issue by mcgriff3325** [atom/teletype#588]
### Diagnostics

```
Request: GET https://api.teletype.atom.io.griffin/protocol-version

```
### Versions

**Teletype version**: v0.13.4
**Atom version**: 1.53.0
**Platform**: win32

**Comment by Josejhfs** [comment]
#594

**Comment by Josejhfs** [comment]
> ### Diagnostics
> ```
> Request: GET https://api.teletype.atom.io.griffin/protocol-version
> ```
> 
> ### Versions
> **Teletype version**: v0.13.4
> **Atom version**: 1.53.0
> **Platform**: win32
